# Generated by Django 5.1.3 on 2024-11-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('saldo', models.FloatField()),
                ('activo', models.IntegerField()),
                ('nivel_satisfaccion', models.IntegerField(choices=[(1, 'Pesimo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')])),
            ],
        ),
    ]
