# Generated by Django 5.1.3 on 2024-11-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_cliente_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='activo',
            new_name='estado_actividad',
        ),
    ]
